import React from "react";
import { TOTAL_ITEMS } from "../../data/checkItems";

/**
 * PDF出力用のテンプレートコンポーネント (ページ分割対応)
 */
const PDFTemplate = React.forwardRef(({ session, categorizedAnswers, yesCount, noCount }, ref) => {
  const PAGE_LIMIT = 24; // 1ページあたりのウェイト上限目安
  const pages = [];
  let currentPageNodes = [];
  let currentWeight = 0;

  // 1. ヘッダー情報の生成 (Weight目安: 8)
  const headerNode = (
    <div key="header">
      <div style={{ textAlign: "center", borderBottom: "2px solid #333", paddingBottom: "10px", marginBottom: "20px" }}>
        <h1 style={{ margin: 0, fontSize: "24px" }}>測量前チェックシート</h1>
      </div>
      <div style={{ marginBottom: "20px" }}>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <tbody>
            <tr>
              <td style={{ padding: "8px", border: "1px solid #ccc", background: "#f9f9f9", width: "120px" }}>現場名</td>
              <td style={{ padding: "8px", border: "1px solid #ccc" }}>{session.siteName}</td>
            </tr>
            <tr>
              <td style={{ padding: "8px", border: "1px solid #ccc", background: "#f9f9f9" }}>点検者</td>
              <td style={{ padding: "8px", border: "1px solid #ccc" }}>{session.inspector}</td>
            </tr>
            <tr>
              <td style={{ padding: "8px", border: "1px solid #ccc", background: "#f9f9f9" }}>実施日時</td>
              <td style={{ padding: "8px", border: "1px solid #ccc" }}>
                {session.completedAt ? new Date(session.completedAt).toLocaleString("ja-JP") : "-"}
              </td>
            </tr>
            <tr>
              <td style={{ padding: "8px", border: "1px solid #ccc", background: "#f9f9f9" }}>結果</td>
              <td style={{ padding: "8px", border: "1px solid #ccc" }}>
                はい: {yesCount}件 / いいえ: {noCount}件 (全{TOTAL_ITEMS}項目)
              </td>
            </tr>
            <tr>
              <td style={{ padding: "8px", border: "1px solid #ccc", background: "#f9f9f9" }}>メモ</td>
              <td style={{ padding: "8px", border: "1px solid #ccc", whiteSpace: "pre-wrap" }}>
                {session.memo || "なし"}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
  
  currentPageNodes.push(headerNode);
  currentWeight += 8;

  // 2. 質問項目のチャンク化
  categorizedAnswers.forEach((cat) => {
    if (currentWeight + 2 > PAGE_LIMIT) {
      pages.push(currentPageNodes);
      currentPageNodes = [];
      currentWeight = 0;
    }
    
    // カテゴリヘッダー
    currentPageNodes.push(
      <div key={`cat-${cat.id}`} style={{ background: "#333", color: "#fff", padding: "5px 10px", fontWeight: "bold", marginBottom: "10px" }}>
        {cat.name}
      </div>
    );
    currentWeight += 2.5;

    cat.answers.forEach((item) => {
      let itemWeight = item.inputs ? 2.5 : 1.5; 
      if (currentWeight + itemWeight > PAGE_LIMIT) {
         pages.push(currentPageNodes);
         currentPageNodes = [];
         currentWeight = 0;
      }
      currentPageNodes.push(
        <div key={`item-${item.id}`} style={{ padding: "10px", borderBottom: "1px solid #eee", display: "flex", alignItems: "flex-start", fontSize: "14px", background: "#fff" }}>
          <span style={{ 
            minWidth: "30px", 
            fontWeight: "bold", 
            color: item.answer === "yes" ? "#10b981" : "#ef4444"
          }}>
            {item.answer === "yes" ? "✓" : "✗"}
          </span>
          <div style={{ flex: 1 }}>
            <div color="#000">{item.question}</div>
            {item.inputs && (
              <div style={{ fontSize: "12px", color: "#666", marginTop: "4px" }}>
                → {Object.entries(item.inputs).map(([k, v]) => `${k}: ${v || '-'}`).join(' / ')}
              </div>
            )}
          </div>
        </div>
      );
      currentWeight += itemWeight;
    });
  });

  // 3. フッター情報
  if (currentWeight + 2 > PAGE_LIMIT) {
     pages.push(currentPageNodes);
     currentPageNodes = [];
  }
  currentPageNodes.push(
     <div key="footer" style={{ marginTop: "20px", textAlign: "right", fontSize: "10px", color: "#999" }}>
       Generated by SurveyCheck PWA - {new Date().toLocaleString()}
     </div>
  );
  pages.push(currentPageNodes);

  return (
    <div 
      ref={ref} 
      className="pdf-container"
      aria-hidden="true"
      style={{ 
        position: "absolute", 
        left: "-9999px", 
        top: 0 
      }}
    >
      {pages.map((pageNodes, idx) => (
        <div key={idx} className="pdf-page" style={{ 
          width: "880px", 
          minHeight: "1244px", // A4縦の比率(297/210)を担保
          backgroundColor: "#ffffff",
          padding: "40px",
          boxSizing: "border-box", // Width内にパディングを含める
          color: "#000000",
          fontFamily: "sans-serif"
        }}>
          {pageNodes}
        </div>
      ))}
    </div>
  );
});

PDFTemplate.displayName = "PDFTemplate";
export default PDFTemplate;
