import React from "react";
import { TOTAL_ITEMS } from "../../data/checkItems";

/**
 * PDF出力用のテンプレートコンポーネント
 * 画面には表示されないが、html2canvasでキャプチャされる
 */
const PDFTemplate = React.forwardRef(({ session, categorizedAnswers, yesCount, noCount }, ref) => {
  return (
    <div 
      ref={ref} 
      className="pdf-container" 
      style={{ 
        position: "absolute", 
        left: "-9999px", 
        top: 0, 
        width: "800px", // A4幅に合わせて固定
        padding: "40px",
        background: "#ffffff",
        color: "#000000",
        fontFamily: "sans-serif"
      }}
    >
      <div style={{ textAlign: "center", borderBottom: "2px solid #333", paddingBottom: "10px", marginBottom: "20px" }}>
        <h1 style={{ margin: 0, fontSize: "24px" }}>測量前チェックシート</h1>
      </div>
      
      <div style={{ marginBottom: "20px" }}>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <tbody>
            <tr>
              <td style={{ padding: "8px", border: "1px solid #ccc", background: "#f9f9f9", width: "120px" }}>現場名</td>
              <td style={{ padding: "8px", border: "1px solid #ccc" }}>{session.siteName}</td>
            </tr>
            <tr>
              <td style={{ padding: "8px", border: "1px solid #ccc", background: "#f9f9f9" }}>点検者</td>
              <td style={{ padding: "8px", border: "1px solid #ccc" }}>{session.inspector}</td>
            </tr>
            <tr>
              <td style={{ padding: "8px", border: "1px solid #ccc", background: "#f9f9f9" }}>実施日時</td>
              <td style={{ padding: "8px", border: "1px solid #ccc" }}>
                {session.completedAt ? new Date(session.completedAt).toLocaleString("ja-JP") : "-"}
              </td>
            </tr>
            <tr>
              <td style={{ padding: "8px", border: "1px solid #ccc", background: "#f9f9f9" }}>結果</td>
              <td style={{ padding: "8px", border: "1px solid #ccc" }}>
                はい: {yesCount}件 / いいえ: {noCount}件 (全{TOTAL_ITEMS}項目)
              </td>
            </tr>
            <tr>
              <td style={{ padding: "8px", border: "1px solid #ccc", background: "#f9f9f9" }}>メモ</td>
              <td style={{ padding: "8px", border: "1px solid #ccc", whiteSpace: "pre-wrap" }}>
                {session.memo || "なし"}
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      {categorizedAnswers.map((cat) => (
        <div key={cat.id} style={{ marginBottom: "20px" }}>
          <div style={{ 
            background: "#333", 
            color: "#fff", 
            padding: "5px 10px", 
            fontWeight: "bold",
            marginBottom: "10px"
          }}>
            {cat.name}
          </div>
          {cat.answers.map((item) => (
            <div key={item.id} style={{ 
              padding: "10px", 
              borderBottom: "1px solid #eee", 
              display: "flex",
              alignItems: "flex-start",
              fontSize: "14px"
            }}>
              <span style={{ 
                minWidth: "30px", 
                fontWeight: "bold", 
                color: item.answer === "yes" ? "#10b981" : "#ef4444"
              }}>
                {item.answer === "yes" ? "✓" : "✗"}
              </span>
              <div style={{ flex: 1 }}>
                <div>{item.question}</div>
                {item.inputs && (
                  <div style={{ fontSize: "12px", color: "#666", marginTop: "4px" }}>
                    → {Object.entries(item.inputs).map(([k, v]) => `${k}: ${v || '-'}`).join(' / ')}
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      ))}
      
      <div style={{ marginTop: "40px", textAlign: "right", fontSize: "10px", color: "#999" }}>
        Generated by SurveyCheck PWA - {new Date().toLocaleString()}
      </div>
    </div>
  );
});

export default PDFTemplate;
